# Error Codes
TSMASTER_ERROR_CODES = {
    0: ("IDX_ERR_OK", "OK"),
    1: ("IDX_ERR_IDX_OUT_OF_RANGE", "Index out of range"),
    2: ("IDX_ERR_CONNECT_FAILED", "Connect failed"),
    3: ("IDX_ERR_DEV_NOT_FOUND", "Device not found"),
    4: ("IDX_ERR_CODE_NOT_VALID", "Error code not valid"),
    5: ("IDX_ERR_ALREADY_CONNECTED", "HID device already connected"),
    6: ("IDX_ERR_HID_WRITE_FAILED", "HID write data failed"),
    7: ("IDX_ERR_HID_READ_FAILED", "HID read data failed"),
    8: ("IDX_ERR_HID_TX_BUFF_OVERRUN", "HID TX buffer overrun"),
    9: ("IDX_ERR_HID_TX_TOO_LARGE", "HID TX buffer too large"),
    10: ("IDX_ERR_PACKET_ID_INVALID", "HID RX packet report ID invalid"),
    11: ("IDX_ERR_PACKET_LEN_INVALID", "HID RX packet length invalid"),
    12: ("IDX_ERR_INTERNAL_TEST_FAILED", "Internal test failed"),
    13: ("IDX_ERR_RX_PACKET_LOST", "RX packet lost"),
    14: ("IDX_ERR_HID_SETUP_DI", "SetupDiGetDeviceInterfaceDetai"),
    15: ("IDX_ERR_HID_CREATE_FILE", "Create file failed"),
    16: ("IDX_ERR_HID_READ_HANDLE", "CreateFile failed for read handle"),
    17: ("IDX_ERR_HID_WRITE_HANDLE", "CreateFile failed for write handle"),
    18: ("IDX_ERR_HID_SET_INPUT_BUFF", "HidD_SetNumInputBuffers"),
    19: ("IDX_ERR_HID_GET_PREPAESED", "HidD_GetPreparsedData"),
    20: ("IDX_ERR_HID_GET_CAPS", "HidP_GetCaps"),
    21: ("IDX_ERR_HID_WRITE_FILE", "WriteFile"),
    22: ("IDX_ERR_HID_GET_OVERLAPPED", "GetOverlappedResult"),
    23: ("IDX_ERR_HID_SET_FEATURE", "HidD_SetFeature"),
    24: ("IDX_ERR_HID_GET_FEATURE", "HidD_GetFeature"),
    25: ("IDX_ERR_HID_DEVICE_IO_CTRL", "Send Feature Report DeviceIoContro"),
    26: ("IDX_ERR_HID_SEND_FEATURE_RPT", "Send Feature Report GetOverLappedResult"),
    27: ("IDX_ERR_HID_GET_MANU_STR", "HidD_GetManufacturerString"),
    28: ("IDX_ERR_HID_GET_PROD_STR", "HidD_GetProductString"),
    29: ("IDX_ERR_HID_GET_SERIAL_STR", "HidD_GetSerialNumberString"),
    30: ("IDX_ERR_HID_GET_INDEXED_STR", "HidD_GetIndexedString"),
    31: ("IDX_ERR_TX_TIMEDOUT", "Transmit timed out"),
    32: ("IDX_ERR_HW_DFU_WRITE_FLASH_FAILED", "HW DFU flash write failed"),
    33: ("IDX_ERR_HW_DFU_WRITE_WO_ERASE", "HW DFU write without erase"),
    34: ("IDX_ERR_HW_DFU_CRC_CHECK_ERROR", "HW DFU crc check error"),
    35: ("IDX_ERR_HW_DFU_COMMAND_TIMED_OUT", "HW DFU reset before crc check success"),
    36: ("IDX_ERR_HW_PACKET_ID_INVALID", "HW packet identifier invalid"),
    37: ("IDX_ERR_HW_PACKET_LEN_INVALID", "HW packet length invalid"),
    38: ("IDX_ERR_HW_INTERNAL_TEST_FAILED", "HW internal test failed"),
    39: ("IDX_ERR_HW_RX_FROM_PC_PACKET_LOST", "HW rx from pc packet lost"),
    40: ("IDX_ERR_HW_TX_TO_PC_BUFF_OVERRUN", "HW tx to pc buffer overrun"),
    41: ("IDX_ERR_HW_API_PARAMETER_INVALID", "HW API parameter invalid"),
    42: ("IDX_ERR_DFU_FILE_LOAD_FAILED", "DFU file load failed"),
    43: ("IDX_ERR_DFU_HEADER_WRITE_FAILED", "DFU header write failed"),
    44: ("IDX_ERR_READ_STATUS_TIMEDOUT", "Read status timed out"),
    45: ("IDX_ERR_CALLBACK_ALREADY_EXISTS", "Callback already exists"),
    46: ("IDX_ERR_CALLBACK_NOT_EXISTS", "Callback not exists"),
    47: ("IDX_ERR_FILE_INVALID", "File corrupted or not recognized"),
    48: ("IDX_ERR_DB_ID_NOT_FOUND", "Database unique id not found"),
    49: ("IDX_ERR_SW_API_PARAMETER_INVALID", "Software API parameter invalid"),
    50: ("IDX_ERR_SW_API_GENERIC_TIMEOUT", "Software API generic timed out"),
    51: ("IDX_ERR_SW_API_SET_CONF_FAILED", "Software API set hw config. failed"),
    52: ("IDX_ERR_SW_API_INDEX_OUT_OF_BOUNDS", "Index out of bounds"),
    53: ("IDX_ERR_SW_API_WAIT_TIMEOUT", "RX wait timed out"),
    54: ("IDX_ERR_SW_API_GET_IO_FAILED", "Get I/O failed"),
    55: ("IDX_ERR_SW_API_SET_IO_FAILED", "Set I/O failed"),
    56: ("IDX_ERR_SW_API_REPLAY_ON_GOING", "An active replay is already running"),
    57: ("IDX_ERR_SW_API_INSTANCE_NOT_EXISTS", "Instance not exists"),
    58: ("IDX_ERR_HW_CAN_TRANSMIT_FAILED", "CAN message transmit failed"),
    59: ("IDX_ERR_HW_NO_RESPONSE", "No response from hardware"),
    60: ("IDX_ERR_SW_CAN_MSG_NOT_FOUND", "CAN message not found"),
    61: ("IDX_ERR_SW_CAN_RECV_BUFFER_EMPTY", "User CAN receive buffer empty"),
    62: ("IDX_ERR_SW_CAN_RECV_PARTIAL_READ", "CAN total receive count <> desired count"),
    63: ("IDX_ERR_SW_API_LINCONFIG_FAILED", "LIN config failed"),
    64: ("IDX_ERR_SW_API_FRAMENUM_OUTOFRANGE", "LIN frame number out of range"),
    65: ("IDX_ERR_SW_API_LDFCONFIG_FAILED", "LDF config failed"),
    66: ("IDX_ERR_SW_API_LDFCONFIG_CMDERR", "LDF config cmd error"),
    67: ("IDX_ERR_SW_ENV_NOT_READY", "TSMaster envrionment not ready"),
    68: ("IDX_ERR_SECURITY_FAILED", "reserved failed"),
    69: ("IDX_ERR_XL_ERROR", "XL driver error"),
    70: ("IDX_ERR_SEC_INDEX_OUTOFRANGE", "index out of range"),
    71: ("IDX_ERR_STRINGLENGTH_OUTFOF_RANGE", "string length out of range"),
    72: ("IDX_ERR_KEY_IS_NOT_INITIALIZATION", "key is not initialized"),
    73: ("IDX_ERR_KEY_IS_WRONG", "key is wrong"),
    74: ("IDX_ERR_NOT_PERMIT_WRITE", "write not permitted"),
    75: ("IDX_ERR_16BYTES_MULTIPLE", "16 bytes multiple"),
    76: ("IDX_ERR_LIN_CHN_OUTOF_RANGE", "LIN channel out of range"),
    77: ("IDX_ERR_DLL_NOT_READY", "DLL not ready"),
    78: ("IDX_ERR_FEATURE_NOT_SUPPORTED", "Feature not supported"),
    79: ("IDX_ERR_COMMON_SERV_ERROR", "common service error"),
    80: ("IDX_ERR_READ_PARA_OVERFLOW", "read parameter overflow"),
    81: ("IDX_ERR_INVALID_CHANNEL_MAPPING", "Invalid application channel mapping"),
    82: ("IDX_ERR_TSLIB_GENERIC_OPERATION_FAILED", "libTSMaster generic operation failed"),
    83: ("IDX_ERR_TSLIB_ITEM_ALREADY_EXISTS", "item already exists"),
    84: ("IDX_ERR_TSLIB_ITEM_NOT_FOUND", "item not found"),
    85: ("IDX_ERR_TSLIB_LOGICAL_CHANNEL_INVALID", "logical channel invalid"),
    86: ("IDX_ERR_FILE_NOT_EXISTS", "file not exists"),
    87: ("IDX_ERR_NO_INIT_ACCESS", "no init access, cannot set baudrate"),
    88: ("IDX_ERR_CHN_NOT_ACTIVE", "the channel is inactive"),
    89: ("IDX_ERR_CHN_NOT_CREATED", "the channel is not created"),
    90: ("IDX_ERR_APPNAME_LENGTH_OUT_OF_RANGE", "length of the appname is out of range"),
    91: ("IDX_ERR_PROJECT_IS_MODIFIED", "project is modified"),
    92: ("IDX_ERR_SIGNAL_NOT_FOUND_IN_DB", "signal not found in database"),
    93: ("IDX_ERR_MESSAGE_NOT_FOUND_IN_DB", "message not found in database"),
    94: ("IDX_ERR_TSMASTER_IS_NOT_INSTALLED", "TSMaster is not installed"),
    95: ("IDX_ERR_LIB_LOAD_FAILED", "Library load failed"),
    96: ("IDX_ERR_LIB_FUNCTION_NOT_FOUND", "Library function not found"),
    97: (
        "IDX_ERR_LIB_NOT_INITIALIZED",
        "cannot find libTSMaster.dll, use 'set_libtsmaster_location' to set its location before calling initialize_lib_tsmaster",
    ),
    98: ("IDX_ERR_PCAN_GENRIC_ERROR", "PCAN generic operation error"),
    99: ("IDX_ERR_KVASER_GENERIC_ERROR", "Kvaser generic operation error"),
    100: ("IDX_ERR_ZLG_GENERIC_ERROR", "ZLG generic operation error"),
    101: ("IDX_ERR_ICS_GENERIC_ERROR", "ICS generic operation error"),
    102: ("IDX_ERR_TC1005_GENERIC_ERROR", "TC1005 generic operation error"),
    103: ("IDX_ERR_SYSTEM_VAR_NOT_FOUND", "System variable not found"),
    104: ("IDX_ERR_INCORRECT_RETURN_VALUE", "incorrect return value"),
    105: ("IDX_ERR_CYCLIC_MSG_NOT_EXIST", "Message not existing, update failed"),
    106: ("IDX_ERR_BAUD_NOT_AVAIL", "Specified baudrate not available"),
    107: ("IDX_ERR_DEV_NOT_SUPPORT_SYNC_SEND", "Device does not support sync. transmit"),
    108: ("IDX_ERR_MP_WAIT_TIME_NOT_SATISFIED", "Wait time not satisfied"),
    109: ("IDX_ERR_CANNOT_OPERATE_WHILE_CONNECTED", "Cannot operate while app is connected"),
    110: ("IDX_ERR_CREATE_FILE_FAILED", "Create file failed"),
    111: ("IDX_ERR_PYTHON_EXECUTE_FAILED", "Execute python failed"),
    112: ("IDX_ERR_SIGNAL_MULTIPLEXED_NOT_ACTIVE", "Current multiplexed signal is not active"),
    113: ("IDX_ERR_GET_HANDLE_BY_CHANNEL_FAILED", "Get handle by logic channel failed"),
    114: (
        "IDX_ERR_CANNOT_OPERATE_WHILE_APP_CONN",
        "Cannot operate while application is connected, please stop application first",
    ),
    115: ("IDX_ERR_FILE_LOAD_FAILED", "File load failed"),
    116: ("IDX_ERR_READ_LINDATA_FAILED", "Read LIN Data Failed"),
    117: ("IDX_ERR_FIFO_NOT_ENABLED", "FIFO not enabled"),
    118: ("IDX_ERR_INVALID_HANDLE", "Invalid handle"),
    119: ("IDX_ERR_READ_FILE_ERROR", "Read file error"),
    120: ("IDX_ERR_READ_TO_EOF", "Read to EOF"),
    121: ("IDX_ERR_CONF_NOT_SAVED", "Configuration not saved"),
    122: ("IDX_ERR_IP_PORT_OPEN_FAILED", "IP port open failed"),
    123: ("IDX_ERR_IP_TCP_CONNECT_FAILED", "TCP connect failed"),
    124: ("IDX_ERR_DIR_NOT_EXISTS", "Directory not exists"),
    125: ("IDX_ERR_CURRENT_LIB_NOT_SUPPORTED", "Current library not supported"),
    126: ("IDX_ERR_TEST_NOT_RUNNING", "Test is not running"),
    127: ("IDX_ERR_SERV_RESPONSE_NOT_RECV", "Server response not received"),
    128: ("IDX_ERR_CREATE_DIR_FAILED", "Create directory failed"),
    129: ("IDX_ERR_INCORRECT_ARGUMENT_TYPE", "Invalid argument type"),
    130: ("IDX_ERR_READ_DATA_PACKAGE_OVERFLOW", "Read Data Package from Device Failed"),
    131: ("IDX_ERR_REPLAY_IS_ALREADY_RUNNING", "Precise replay is running"),
    132: ("IDX_ERR_REPALY_MAP_ALREADY_EXIST", "Replay map is already exist"),  # Possible typo in original message.
    133: ("IDX_ERR_USER_CANCEL_INPUT", "User cancel input"),
    134: ("IDX_ERR_API_CHECK_FAILED", "API check result is negative"),
    135: ("IDX_ERR_CANABLE_GENERIC_ERROR", "CANable generic error"),
    136: ("IDX_ERR_WAIT_CRITERIA_NOT_SATISFIED", "Wait criteria not satisfied"),
    137: ("IDX_ERR_REQUIRE_APP_CONNECTED", "Operation requires application connected"),
    138: ("IDX_ERR_PROJECT_PATH_ALREADY_USED", "Project path is used by another application"),
    139: ("IDX_ERR_TP_TIMEOUT_AS", "Timeout for the sender to transmit data to the receiver"),
    140: ("IDX_ERR_TP_TIMEOUT_AR", "Timeout for the receiver to transmit flow control to the sender"),
    141: ("IDX_ERR_TP_TIMEOUT_BS", "Timeout for the sender to send first data frame after receiving FC frame"),
    142: ("IDX_ERR_TP_TIMEOUT_CR", "Timeout for the receiver to receiving first CF frame after sending FC frame"),
    143: ("IDX_ERR_TP_WRONG_SN", "Serial Number Error"),
    144: ("IDX_ERR_TP_INVALID_FS", "Invalid flow status of the flow control frame"),
    145: ("IDX_ERR_TP_UNEXP_PDU", "Unexpected Protocol Data Unit"),
    146: ("IDX_ERR_TP_WFT_OVRN", "Wait counter of the FC frame out of the maxWFT"),
    147: ("IDX_ERR_TP_BUFFER_OVFLW", "Buffer of the receiver is overflow"),
    148: ("IDX_ERR_TP_NOT_IDLE", "TP Module is busy"),
    149: ("IDX_ERR_TP_ERROR_FROM_CAN_DRIVER", "There is error from CAN Driver"),
    150: ("IDX_ERR_TP_HANDLE_NOT_EXIST", "Handle of the TP Module is not exist"),
    151: ("IDX_ERR_UDS_EVENT_BUFFER_IS_FULL", "UDS event buffer is full"),
    152: ("IDX_ERR_UDS_HANDLE_POOL_IS_FULL", "Handle pool is full, can not add new UDS module"),
    153: ("IDX_ERR_UDS_NULL_POINTER", "Pointer of UDS module is null"),
    154: ("IDX_ERR_UDS_MESSAGE_INVALID", "UDS message is invalid"),
    155: ("IDX_ERR_UDS_NO_DATA", "No uds data received"),
    156: ("IDX_ERR_UDS_MODULE_NOT_EXISTING", "Handle of uds is not existing"),
    157: ("IDX_ERR_UDS_MODULE_NOT_READY", "UDS module is not ready"),
    158: ("IDX_ERR_UDS_SEND_DATA_FAILED", "Transmit UDS frame data failed"),
    159: ("IDX_ERR_UDS_NOT_SUPPORTED", "This UDS Service is not supported"),
    160: ("IDX_ERR_UDS_TIMEOUT_SENDING_REQUEST", "Timeout to send uds request"),
    161: ("IDX_ERR_UDS_TIMEOUT_GET_RESPONSE", "Timeout to get uds response"),
    162: ("IDX_ERR_UDS_NEGATIVE_RESPONSE", "Get uds negative response"),
    163: ("IDX_ERR_UDS_NEGATIVE_WITH_EXPECTED_NRC", "Get uds negative response with expected NRC"),
    164: ("IDX_ERR_UDS_NEGATIVE_UNEXPECTED_NRC", "Get uds negative response with unexpected NRC"),
    165: ("IDX_ERR_UDS_CANTOOL_NOT_READY", "UDS CAN Tool is not ready"),
    166: ("IDX_ERR_UDS_DATA_OUTOF_RANGE", "UDS Data outof range"),
    167: ("IDX_ERR_UDS_UNEXPECTED_FRAME", "Get Unexpected UDS frame"),
    168: (
        "IDX_ERR_UDS_UNEXPECTED_POSTIVE_RESPONSE",
        "Receive unpexted positive response frame",
    ),  # Possible typo in original message.
    169: (
        "IDX_ERR_UDS_POSITIVE_REPONSE_WITH_WRONG_DATA",
        "Receive positive response with wrong data",
    ),  # Possible typo in original message.
    170: ("IDX_ERR_UDS_GET_POSITIVE_RESPONSE_FAILED", "Failed to get positive response"),
    171: ("IDX_ERR_UDS_MaxNumOfBlockLen_OVER_FLOW", "MaxNumOfBlockLen out of range"),
    172: ("IDX_ERR_UDS_NEGATIVE_RESPONSE_WITH_UNEXPECTED_NRC", "Receive negative response with unexpected NRC"),
    173: ("IDX_ERR_UDS_SERVICE_IS_RUNNING", "UDS service is busy"),
    174: ("IDX_ERR_UDS_NEED_APPLY_DOWNLOAD_FIRST", "Apply download first before transfer data"),
    175: ("IDX_ERR_UDS_RESPONSE_DATA_LENGTH_ERR", "Length of the uds response is wrong"),
    176: ("IDX_ERR_TEST_CHECK_LOWER", "Verdict value smaller than specification"),
    177: ("IDX_ERR_TEST_CHECK_UPPER", "Verdict value greater than specification"),
    178: ("IDX_ERR_TEST_VERDICT_CHECK_FAILED", "Verdict check failed"),
    179: ("IDX_ERR_AM_NOT_LOADED", "Graphic Program not loaded, please load it first"),
    180: ("IDX_ERR_PANEL_NOT_FOUND", "Panel not found"),
    181: ("IDX_ERR_CONTROL_NOT_FOUND_IN_PANEL", "Control not found in panel"),
    182: ("IDX_ERR_PANEL_NOT_LOADED", "Panel not loaded, please load it first"),
    183: ("IDX_ERR_STIM_SIGNAL_NOT_FOUND", "STIM signal not found"),
    184: ("IDX_ERR_AM_SUB_MODULE_NOT_AVAIL", "Graphic Program sub module not available"),
    185: ("IDX_ERR_AM_VARIANT_GROUP_NOT_FOUND", "Graphic Program variant group not found"),
    186: ("IDX_ERR_PANEL_CONTROL_NOT_FOUND", "Control not found in panel"),
    187: ("IDX_ERR_PANEL_CONTROL_NOT_SUPPORT_THIS", "Panel control does not support this property"),
    188: ("IDX_ERR_RBS_NOT_RUNNING", "RBS engine is not running"),
    189: ("IDX_ERR_MSG_NOT_SUPPORT_PDU_CONTAINER", "This message does not support PDU container"),
    190: ("IDX_ERR_DATA_NOT_AVAILABLE", "Data not available"),
    191: ("IDX_ERR_J1939_NOT_SUPPORTED", "J1939 not supported"),
    192: (
        "IDX_ERR_J1939_ANOTHER_PDU_IS_SENDING",
        "Transmit J1939 PDU failed due to another PDU is already being transmitted",
    ),
    193: ("IDX_ERR_J1939_TX_FAILED_PROTOCOL_ERROR", "Transmit J1939 PDU failed due to protocol error"),
    194: ("IDX_ERR_J1939_TX_FAILED_NODE_INACTIVE", "Transmit J1939 PDU failed due to node inactive"),
    195: ("IDX_ERR_NO_LICENSE", "API is called without license support"),
    196: ("IDX_ERR_SIGNAL_CHECK_RANGE_VIOLATION", "Signal range check violation"),
    197: ("IDX_ERR_LOG_READ_CATEGORY_FAILED", "DataLogger read category failed"),
    198: ("IDX_ERR_CHECK_BOOT_VERSION_FAILED", "Check Flash Bootloader Version Failed"),
    199: ("IDX_ERR_LOG_FILE_NOT_CREATED", "Log file not created"),
    200: ("IDX_ERR_MODULE_IS_BEING_EDITED_BY_USER", "the current module is being edited by user in dialog"),
    201: ("IDX_ERR_LOG_DEVICE_IS_BUSY", "The Logger device is busy, can not operation at the same time"),
    202: ("IDX_ERR_LIN_MASTER_TRANSMIT_N_AS_TIMEOUT", "Master node transmit diagnostic package timeout"),
    203: ("IDX_ERR_LIN_MASTER_TRANSMIT_TRANSMIT_ERROR", "Master node transmit frame failed"),
    204: ("IDX_ERR_LIN_MASTER_REV_N_CR_TIMEOUT", "Master node receive diagnostic package timeout"),
    205: ("IDX_ERR_LIN_MASTER_REV_ERROR", "Master node receive frame failed"),
    206: ("IDX_ERR_LIN_MASTER_REV_INTERLLEAVE_TIMEOUT", "Internal time runs out before reception is completed"),
    207: ("IDX_ERR_LIN_MASTER_REV_NO_RESPONSE", "Master node received no response"),
    208: ("IDX_ERR_LIN_MASTER_REV_SN_ERROR", "Serial Number Error when receiving multi frames"),
    209: ("IDX_ERR_LIN_SLAVE_TRANSMIT_N_CR_TIMEOUT", "Slave node transmit diagnostic package timeout"),
    210: ("IDX_ERR_LIN_SLAVE_REV_N_CR_TIMEOUT", "Slave node receive diagnostic pacakge timeout"),
    211: ("IDX_ERR_LIN_SLAVE_TRANSMIT_ERROR", "Slave node transmit frames error"),
    212: ("IDX_ERR_LIN_SLAVE_REV_ERROR", "Slave node receive frames error"),
    213: ("IDX_ERR_CLOSE_FILE_FAILED", "Close file failed"),
    214: ("IDX_ERR_CONF_LOG_FILE_FAILED", "Configure log file failed"),
    215: ("IDX_ERR_CONVERT_LOG_FAILED", "Convert log file failed"),
    216: ("IDX_ERR_HALTED_DUE_TO_USER_BREAK", "Operation halted due to user break"),
    217: ("IDX_ERR_WRITE_FILE_FAILED", "Write file failed"),
    218: ("IDX_ERR_UNKNOWN_OBJECT_DETECTED", "Unknown object detected"),
    219: ("IDX_ERR_THIS_FUNC_SHOULD_BE_CALLED_IN_MP", "this function should be called in mini program thread"),
    220: ("IDX_ERR_USER_CANCEL_WAIT", "user canceled wait"),
    221: ("IDX_ERR_DECOMPRESS_DATA_FAILED", "Decompress data failed"),
    222: ("IDX_ERR_AUTOMATION_OBJ_NOT_CREATED", "Automation object not created"),
    223: ("IDX_ERR_ITEM_DUPLICATED", "Item duplicated"),
    224: ("IDX_ERR_DIVIDE_BY_ZERO", "Divide by zero"),
    225: ("IDX_ERR_REQUIRE_MINI_PROGRAM_RUNNING", "This operation requires mini program running"),
    226: ("IDX_ERR_FORM_NOT_EXIST", "Form not exists"),
    227: ("IDX_ERR_CANNOT_CONFIG_WHEN_DEVICE_RUNNING", "Can not config when the device is running"),
    228: ("IDX_ERR_DATA_NOT_READY", "The data of the device is not ready"),
    229: ("IDX_ERR_STOP_DEVICE_FAILED", "Stop device failed"),
    230: ("IDX_ERR_PYTHON_CODE_CRASH", "Python code crashed"),
    231: ("IDX_ERR_CONDITION_NOT_MET", "Condition not met"),
    232: ("IDX_ERR_PYTHON_MODULE_NOT_DEPLOYED", "Cannot call API because Python module not deployed"),
    233: ("IDX_ERR_UDS_CONNECT_DUT_FAILED", "Connect Ethernet DUT Failed"),
    234: ("IDX_ERR_ETH_GENERIC_ACK", "Generic ACK of DOIP Frame"),
    235: ("IDX_ERR_ETH_VEHILCE_INFO_RES", "Response of Vehicle Information"),
    236: ("IDX_ERR_ETH_ACTIVATE_RES", "Response of Active Request"),
    237: ("IDX_ERR_ETH_ALIVE_RES", "Response of Alive Request"),
    238: ("IDX_ERR_ETH_NODE_STATE_RES", "Response of Node State"),
    239: ("IDX_ERR_ETH_DIAG_POWER_MODE_RES", "Response of Diagnostic Power Mode"),
    240: ("IDX_ERR_ETH_DIAG_POSITIVE_ACK", "Positive ACK of Diagnostic Request"),
    241: ("IDX_ERR_ETH_DIAG_NEGATIVE_ACK", "Negative ACK of Diagnostic Request"),
    242: ("IDX_ERR_ETH_VEHICLE_REQ_ID", "Vehicle ID Request"),
    243: ("IDX_ERR_ETH_VEHICLE_REQ_EID_ID", "Vehicle ID with EID Request"),
    244: ("IDX_ERR_ETH_VEHICLE_REQ_VIN_ID", "Vehicle ID with VIN Request"),
    245: ("IDX_ERR_ETH_ACTIVE_REQ", "Routing Activation Request"),
    246: ("IDX_ERR_ETH_ALIVE_REQ", "Alive Check Request"),
    247: ("IDX_ERR_ETH_NODE_STATE_REQ", "Node State Request"),
    248: ("IDX_ERR_ETH_DIAG_POWER_MODE_REQ", "Diagnostic Power Mode Request"),
    249: ("IDX_ERR_ETH_DIAG_REQ_RES", "DOIP Reqeust And Response"),
    250: (
        "IDX_ERR_SOCKET_PREPARE_ENVIROMENT_FIRST",
        "Please prepare enviroment in TSMaster first",
    ),  # Possible typo in original message.
    251: ("IDX_ERR_ETH_RESERVED1", "Reserved1 for Ethernet"),
    252: ("IDX_ERR_GP_MODULE_NOT_FOUND", "Graphic program module not found"),
    253: ("IDX_ERR_GP_ACTION_NOT_FOUND", "Graphic program action not found"),
    254: ("IDX_ERR_GP_CANNOT_INSERT_GOTO_BETWEEN_ACTIONS", "Graphic program Cannot insert goto between actions"),
    255: ("IDX_ERR_GP_CANNOT_DELETE_ACTION_WITH_BOTH_DIR", "Graphic program Cannot delete action with both directions"),
    256: ("IDX_ERR_GP_ENTRY_POINT_CANNOT_BE_DELETED", "Graphic program entry point cannot be deleted"),
    257: ("IDX_ERR_GP_KIND_CANNOT_BE_CHANGED", "Graphic program action type cannot be changed"),
    258: ("IDX_ERR_GP_INCORRECT_ACTION_TYPE", "Graphic program incorrect action type being edited"),
    259: ("IDX_ERR_GP_INCORRECT_EXECUTION_KIND", "Graphic program incorrect execution kind being edited"),
    260: ("IDX_ERR_GP_ACTION_GROUP_REQUIRED", "Graphic program action group required"),
    261: ("IDX_ERR_GP_CANNOT_ADD_DOWNWARD_ACTION", "Graphic program cannot add downward action"),
    262: ("IDX_ERR_GP_CANNOT_ADD_RIGHTWARD_ACTION", "Graphic program cannot add rightward action"),
    263: ("IDX_ERR_RBS_NODE_SIMULATION_IS_NOT_ACTIVE", "RBS node simulation is not active"),
    264: ("IDX_ERR_RBS_FRAME_INFO_NOT_FOUND", "RBS frame info not found"),
    265: ("IDX_ERR_RBS_IS_NOT_ENABLED", "RBS engine is not enabled"),
    266: ("IDX_ERR_GPG_EXCEL_FORMAT_INVALID", "Graphic program generator excel format invalid"),
    267: ("IDX_ERR_GPG_EXCEL_UNKNOWN_OBJ", "Graphic program generator excel unknown object"),
    268: ("IDX_ERR_GPG_EXCEL_OBJ_NOT_FOUND", "Graphic program generator excel object not found"),
    269: ("IDX_ERR_GPG_EXCEL_OBJ_NOT_DEFINED", "Graphic program generator excel object not defined"),
    270: ("IDX_ERR_MP_CODE_CRASH", "Mini program code crash"),
    271: ("IDX_ERR_USER_ABORTED_OPERATION", "User aborted operation"),
    272: ("IDX_ERR_INVALID_MEMORY_ADDRESS", "Invalid memory address"),
    273: ("IDX_ERR_IP_FRAGMENTATION_NEED", "Fragmentation is needed when building IPv4 packet"),
    274: ("IDX_ERR_IP_IPV4_ID_REQUIRED", "IPv4 Id is required"),
    275: ("IDX_ERR_SYS_VAR_NOT_EXISTS", "System variable not exists"),
    276: (
        "IDX_ERR_WRITE_DEVICE_INT_CONFIG_FAILED",
        "Write internal configuration of Device(such as TC1011 Etc) Failed",
    ),
    277: ("IDX_ERR_READ_DEVICE_INT_CONFIG_FAILED", "Read internal configuration of Device(such as TC1011 Etc) Failed"),
    278: ("IDX_ERR_ARGUMENT_COUNT_DIFFER", "API caller argument count differ"),
    279: ("IDX_ERR_API_CALLER_CALL_FAILED", "API caller call API failed"),
    280: ("IDX_ERR_ETH_FRAME_IS_NOT_IP", "Current ethernet frame is not IP frame"),
    281: ("IDX_ERR_ETH_FRAME_IS_NOT_TCP", "Current ethernet frame is not TCP frame"),
    282: ("IDX_ERR_ETH_FRAME_IS_NOT_UDP", "Current ethernet frame is not UDP frame"),
    283: ("IDX_ERR_ETH_FRAME_DOES_NOT_CONTAIN_CRC", "Current ethernet frame does not contain CRC"),
    284: ("IDX_ERR_ETH_API_REQUIRES_SINGLE_FRAME", "This API requires single frame, not fragment frame"),
    285: ("IDX_ERR_ITEM_NOT_ENABLED", "This item is not enabled in configuration"),
    286: ("IDX_ERR_ITEM_CONFIGURATION_NOT_VALID", "This item configuration is not valid"),
    287: ("IDX_ERR_RESERVED01", "Reserved definition"),
    288: ("IDX_ERR_SHOULD_START_BATCH_FIRST", "Should start batch first before this operation"),
    289: ("IDX_ERR_TEST_SYSTEM_MODULE_NOT_LOADED", "Test system module not loaded"),
    290: ("IDX_ERR_VISA_COMMAD_FAILED", "VISA Command failed"),  # Possible typo in original message.
    291: ("IDX_ERR_VISA_DEVICE_NOT_READY", "VISA Device not ready"),
    292: ("IDX_ERR_ADD_INSTRUMENT_FAILED", "Add new instrument failed"),
    293: ("IDX_ERR_LANG_KEY_NOT_FOUND", "Language item not found ini ini file"),  # Possible typo in original message.
    294: (
        "IDX_ERR_MAC_ADDRESS_NOT_EXITS",
        "Mac Address not exists in router table",
    ),  # Possible typo in original message.
    295: ("IDX_ERR_IP_PORT_NOT_EXISTS", "IP and Port not exists in router table"),
    296: ("IDX_ERR_CRITICAL_SECTION_ENTER_FAILED", "Critical section try enter failed"),
    297: ("IDX_ERR_REQUIRE_APP_DISCONNECTED", "This operation requires application disconnected"),
    298: ("IDX_ERR_SOCKET_ALREADY_EXISTS", "This socket is ready exists"),
    299: ("IDX_ERR_SOCKET_NOT_EXISTS", "This socket is not exists"),
    300: ("IDX_ERR_INVALID_IPV4_ENDPOINT", "The IPV4 Endpoint is invalid"),
    301: ("IDX_ERR_TCP_CLIENT_NOT_SUPPORT_THIS_FEATURE", "TCP Client not support this feature"),
    302: ("IDX_ERR_TCP_SERVER_NOT_SUPPORT_THIS_FEATURE", "TCP Server not support this feature"),
    303: ("IDX_ERR_TCP_CLIENT_CONNECT_FAILED", "TCP Client connect to server failed"),
    304: ("IDX_ERR_TCP_START_LISTEN_FAILED", "TCP Server start listen failed"),
    305: ("IDX_ERR_TCP_DUPLICATE_START_LISTEN", "TCP Server start listen repeatedly is not allowed"),
    306: ("IDX_ERR_CREATE_SOCKET_FAILED", "Create socket failed"),
    307: ("IDX_ERR_RPC_SERVER_NOT_ACTIVATED", "RPC Server not activated"),
    308: ("IDX_ERR_RPC_CLIENT_NOT_ACTIVATED", "RPC Client not activated"),
    309: ("IDX_ERR_RPC_CALL_FAILED", "RPC call failed"),
    310: ("IDX_ERR_TSMASTER_NOT_IN_COSIMULATION", "TSMaster is not in co-simulation mode"),
    311: ("IDX_ERR_OBJECT_NOT_CREATED", "Object not created"),
    312: ("IDX_ERR_OPERATION_NOT_SUPP_IN_BATCH_MODE", "Operation not supported in batch mode"),
    313: ("IDX_ERR_NOT_IMPLEMENTED", "Not implemented"),
    314: ("IDX_ERR_OPERATION_PENDING", "Operation is pending"),
    315: ("IDX_ERR_COMPILE_FAILED", "Compile failed"),
    316: ("IDX_ERR_RPC_SERVER_RUN_FAILED", "Rpc Server run failed"),
    317: ("IDX_ERR_RPC_COMMAND_INVALID", "Invalid Rpc Command"),
    318: ("IDX_ERR_INIT_SIMULATION_FAILED", "Initialize simulation failed"),
    319: ("IDX_ERR_SIM_RUN_TO_END", "Simulation has run to end"),
    320: ("IDX_ERR_SIM_VAR_INVALID", "Simulation variable invalid"),
    321: ("IDX_ERR_COM_SERVER_FAILED", "COM server encounter error"),
    322: ("IDX_ERR_APP_NOT_CONNECTED", "Current application is not connected"),
    323: ("IDX_ERR_LOGIN_FAILED", "Login failed")
}
