name: basic checks

on: pull_request

jobs:
  basic_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - run: |
        pip install pipx
        pipx install poetry
        poetry install
        npm install -g markdownlint-cli
    - run: poetry run isort --diff --check vta
      if: always()
    - run: poetry run black --diff --check vta
      if: always()
    - run: poetry run flake8 vta
      if: always()
    - run: poetry run mypy vta
      if: always()
    - run: poetry run ensure_header --check
      if: always()
    - name: Run markdownlint
      run: markdownlint '**/*.md'
      if: always()